web:
  build: ./app
  ports:
    - "8888:8888"
  volumes:
    - .:/app
  links:
    - postgres:postgres

nginx:
  build: ./nginx/
  ports:
    - "8080:8080"

postgres:
  image: postgres
  ports:
    - "5432:5432"
    
